### ISSUE TITLE
iOS empty notification

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-alert-app#1024]
# Summary

Not sure how to recreate or the cause of this yet but iOS 13.6 (possibly other versions) the os is showing an "empty" notification.  I was able to capture a screen on my "dev phone".  The app is showing no exposure.

We have other reports of this happening as well.

> received an alert, closed the notification and then went into the app and it said there was no exposure.

<img width="300" src="https://user-images.githubusercontent.com/62242/89780799-1ea6d180-dae0-11ea-98d7-77d58dd1c2eb.jpg">

# Environment

> iOS

**Comment by lchski** [comment]
Theory about this (just spitballing):

- This "empty" notification may be because the phone is locked, so it doesn't display the full notification content.
- This appears to be not a notification from the app itself, but from the underlying framework. I believe this is the framework giving its weekly update or something like that, saying "we checked for exposures X times". Can definitely be confusing, as it's not a notification actually from the app.

Apologies if both of these were already on your radar!

**Comment by sanchitgera** [comment]
I got a similar notification this morning. However, the full contents of the notification was something along the lines of "We found 0 instances of exposure in the last week". It can definitely be confusing and lead to some false alarms (even if momentary). Maybe we should look into ways of suppressing this notification if possible?

**Comment by emilykuret** [comment]
Agree with @lchski. This seems to be caused by a setting on the OS around how the user has set how they can view their notifications.

**Comment by jeberhardt** [comment]
This is controlled under **Settings** --> **Notifications** --> **Show Previews** --> **When Unlocked**

@timarney - I would consider this to be not a bug.

**Comment by jeberhardt** [comment]
>
> > received an alert, closed the notification and then went into the app and it said there was no exposure.
> 

There could be other notifications, either by the app or the os, that aren't necessarily due to an exposure being triggered. So opening the app could still indicate _no exposure_.

**Comment by timarney** [comment]
Closing this as it's an OS level issue.
