### ISSUE TITLE
"Bluetooth is off" behaviour is not displaying expected results.

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/covid-alert-app#1073]
# Summary | Résumé

If Bluetooth is turned off, the user will be shown a screen that indicates Bluetooth is off. This is good if the user is in "monitoring" state, but if they are in "exposed" or "diagnosed" state, then this screen will prevent them from taking any further action.

While Bluetooth is required to collect and broadcast IDs, it is not required to submit daily keys or to see the current exposed state.
![Screenshot_20200821-151050](https://user-images.githubusercontent.com/77435/90929248-5eb26200-e3c6-11ea-9a32-00997e58712d.png)

# Steps to reproduce | Étapes à reproduire

### "Diagnosed" State
1. Launch the app.
2. Enter a one-time-key, and put the user in "diagnosed" state. Follow the prompt to upload the daily keys.
3. Return the app the next day.
4. Turn Bluetooth off. Launch the app.
5. The "Bluetooth Off" screen should appear, preventing the user from uploading the new daily keys.

### "Exposed" State
1. Launch the app.
2. Follow normal process to put this phone into an "exposed" state.
3. Turn Bluetooth off. Launch the app.
4. The "Bluetooth Off" screen should appear, preventing the user from seeing the screen telling them they are in an exposed state, along with the instructions on what to do.

# Environment | Environnement logiciel

iOS and Android

# Suggested Solution
- For the "exposed" and "diagnosed" states, display the normal content, but provide the error status at the bottom of the screen. See screenshots below for examples.
- Add an additional line of text to the error, below "COVID Alert is off", to indicate the specific problem being: "Bluetooth is off"

![Exposure-ON-bottom](https://user-images.githubusercontent.com/77435/90929358-91f4f100-e3c6-11ea-8d53-579205734b43.png)
![DiagnosedShare](https://user-images.githubusercontent.com/77435/90929378-9b7e5900-e3c6-11ea-8e43-36c5138fb750.png)

**Comment by amazingphilippe** [comment]
### Here's what this issue can fix:
- Rework logic hierarchy so that we prioritize "Exposed" and "diagnosed" states over Bluetooth OFF phone state. 
- Make sure that Bluetooth OFF can't prevent people to collect new random ids to upload during subsequent days. 

### Here's what is beyond this issue, but very relevant to include in our design debt:
- Adding more information to the closed shield. See issue #769 to understand why we don't want to add anymore elements to the shield. More information about "COVID Alert is off" can always be found in the menu. 
- Reworking the UI to include multiple app states at once, whether they are phone states or exposure states
