### ISSUE TITLE
App should not request location to be enabled on Android 11

### ISSUE THREAD

**Issue by ajayyy** [cds-snc/covid-alert-app#1130]
This requirement was removed on Android 11.

https://developers.google.com/android/exposure-notifications/release-notes#locationless_scanning

The generic `deviceSupportsLocationlessScanning()` can be used

**Comment by timarney** [comment]
Noting this is on our radar and is in our backlog :)

Will update here in the future.

**Comment by 100terres** [comment]
@timarney 

I personally almost uninstalled the app because I did not understand why it was "deactivated". When I clicked on "Activer Alert COVID" it only explain that I need to active the Bluetooth nothing about the localization. There is a text below the CTA explaining the location need to be activated... But I think it is not clear enough !

![signal-2020-10-06-143416](https://user-images.githubusercontent.com/4420524/95246255-36e65480-07e2-11eb-9326-9710845bc7ee.png)
![signal-2020-10-06-143753](https://user-images.githubusercontent.com/4420524/95246254-364dbe00-07e2-11eb-99ac-f45ee42912f4.png)
![signal-2020-10-06-144206](https://user-images.githubusercontent.com/4420524/95246250-364dbe00-07e2-11eb-8773-200da51b4e15.png)

**Comment by timarney** [comment]
@100terres @ajayyy it's on the priority list - we'll get to it as soon as we possibly can.

**Comment by 100terres** [comment]
Thank you ! @timarney :upside_down_face:

**Comment by timarney** [comment]
FYI - This rolled out in the latest release 1.0.12.
