### ISSUE TITLE
Bug: App either fails to leave "You've been exposed" state on time or does not announce new exposures

### ISSUE THREAD

**Issue by davidrusak** [cds-snc/covid-alert-app#1192]
# Summary | Résumé

If the app registers an exposure, you get a push notif and it enters the state where it says "You've been exposed in the last 14 days". On my phone the app has now been in this state for 22 days. If I had a fresh exposure which caused the 14 day timer to reset, it failed to notify me. 

If it is skipping that notification, that seems like a severe issue -- worsened by the fact that, even if you do go check the app yourself in this state, there's no way to verify when the exposure it's now referring to happened or how many of them there have been, making this indistinguishable from the app's state after the first exposure.

# Steps to reproduce | Étapes à reproduire

- I received an exposure notification Sept 17
- I got tested Sept 17 and a negative result Sept 18
- The only road the app offers out of this state is to report a positive test result. There seems to be no prescribed action or way to dismiss the state if you test negative, so I just monitored the app daily to see when it would stop showing "You've been exposed in the last 14 days"
- It still hasn't as of Oct 9, 22 days later. Either it is stuck in this state longer than it's meant to be, or a fresh exposure occurred silently at some point in the interim.

# Environment | Environnement logiciel

iOS 13 on iPhone 11

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

There may be designed reasons why the "You've been exposed" state is impossible to dismiss, but as a user it was surprising and weird to not be able to get it out of this state, and made me immediately distrust whether the app was doing its job while it was still stuck showing me that exposure notice -- as it turns out it maybe was not.

**Comment by raidendingo** [comment]
Came here for a similar issue. The parameters of how notifications arrive and are dismissed are unclear. Saw an exposure notification on Oct 10 and it was gone on Oct 11. 

It would be most effective to know the date of each exposure and have a history of all exposures. This may also be helpful in determining the accuracy of the test you take as its more effective a few days after exposure.

**Comment by timarney** [comment]
COVID Alert’s “You’ve been exposed” homescreen status goes away 14 days after an exposure has been detected. 
If the “You’ve been exposed” screen remains on your app’s homescreen for longer than 14 days, it is in this state because of new, or multiple exposures. 

If you see the “You’ve been exposed screen,” you should follow all public health advice for your region.
We appreciate your feedback letting us know that you did not receive a push notification from the app to alert you of this new exposure. The team is currently working on improving this experience, and you reaching out helps us a great deal.
