### ISSUE TITLE
Android to android 'No exposure message' after 24hrs of exposure (Ver 53)

### ISSUE THREAD

**Issue by ndolter** [cds-snc/covid-alert-app#768]
Test case = 26
Samsung Galaxy version 8
Battery % = 100%
OS is set to English
App ver = 53
UUID= RmbqAZUo6c4

July 16 @ 2:21pm set device (Android ver 8) next to a positively diagnosed device (Samsung Galaxy, ver 7) for +15 mins &< 2 feet apart
Expected result = After 24 hours a push notification is displayed on closed screen and msg on home screen = You have been exposed
Actual Result = After 26 hours, neither message was received, instead the device displays ''No exposure detected' on Samsung 7

Checked on on July 18th @ 8:30am and the device received the 'You've been exposed in the last 14 days' message

Xref Issue #681

> @ndolter can you confirm which version of the app you are using?

@JuliannaR It's app ver 53

**Comment by JuliannaR** [comment]
@ndolter can you confirm which version of the app you are using?

**Comment by mmiron-HC** [comment]
Retested this one. 
device 1: iphone 8 +diagnosed EN OS
device 2: Samsung S8 Android v9 FR OS
Exposed on July 17 @ 124 pm - for +15 mins 
Battery % at time of exposure: 
S8: 57%
iPhone 8: 87%

July 18, no push notifications COVID checks show no keys shared/no matched keys.
July 19, no push notificaitons COVID checks show no keys shared/no matched keys.
July 20, no push notificaitons COVID checks show no keys shared/no matched keys.
All COVID Checks show no keys shared/no matched keys
Upgraded app several times over weekend. 

S8 is sitting next to other devices which are not +diagnosed.
Opened the app July 20 - No exposure detected (FR) 
Expected behaviour: push notification should be rec'd ~24hrs after and message You have been exposed (FR) should appear on Home screen.

**Comment by timarney** [comment]
Ref: https://github.com/cds-snc/covid-shield-mobile/issues/740#issuecomment-661277970

**Comment by timarney** [comment]
This should be re-tested if possible.

**Comment by emilykuret** [comment]
Configurations will be retested - closing this issue.
