### ISSUE TITLE
UI issue when viewing the app in landscape. The last checked label is not visible.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#955]
![image](https://user-images.githubusercontent.com/17616596/88847181-acb3bb80-d1b4-11ea-9db8-c3b3be7e2c0b.png)

"Android UI suggestion would be for the bottom panel to be hidden when a user hit the back hardware key instead of closing the app."

source: https://twitter.com/ali_almunayer/status/1287566491924271104/photo/1

**Comment by joshpc** [comment]
Design changes aside, it would be pretty straight forward to update `contentInset` (similar to what I proposed on https://github.com/cds-snc/covid-alert-app/pull/855) on these pages equal to the height of the menu to ensure that the entirety of the content is scrollable. It's not ideal since you can be playing with some pretty tiny screens and the menu will leave an unusable amount of space, but is a step in the right direction.

**Comment by timarney** [comment]
Fixed in https://github.com/cds-snc/covid-alert-app/pull/971
